#!/usr/bin/env node
// Builds the static site into docs/ (what GitHub Pages serves). No dependencies.
//   node build.mjs            -> ./docs
//   node build.mjs --out DIR  -> DIR (the tests build into a temp dir and diff)
import { mkdirSync, rmSync, writeFileSync, readdirSync, copyFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE } from './site.config.mjs';
import { PAGES } from './src/pages.mjs';
import { makeCtx, renderPage } from './src/layout.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outArg = process.argv.indexOf('--out');
const OUT = outArg > -1 ? process.argv[outArg + 1] : join(here, 'docs');

function copyDir(from, to) {
  mkdirSync(to, { recursive: true });
  for (const name of readdirSync(from)) {
    if (name.startsWith('.')) continue;
    const a = join(from, name), b = join(to, name);
    if (statSync(a).isDirectory()) copyDir(a, b); else copyFileSync(a, b);
  }
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
copyDir(join(here, 'src/assets'), join(OUT, 'assets'));

// Only what the browser needs. Rates are omitted entirely when prices are hidden.
const browserConfig = {
  phoneE164: SITE.phone.e164,
  email: SITE.email,
  showPrices: SITE.showPrices,
  rates: SITE.showPrices ? SITE.rates : null,
};
writeFileSync(join(OUT, 'assets/config.js'),
  `/* Generated by build.mjs from site.config.mjs. */\nwindow.BB_CONFIG = ${JSON.stringify(browserConfig)};\n`);

const sitemap = [];
for (const page of PAGES) {
  const is404 = page.slug === '404';
  const ctx = makeCtx(SITE, page.slug, { absolute: is404 });
  const html = renderPage(ctx, page);
  const rel = page.file || (page.slug ? `${page.slug}/index.html` : 'index.html');
  mkdirSync(dirname(join(OUT, rel)), { recursive: true });
  writeFileSync(join(OUT, rel), html);
  if (page.inSitemap !== false && !page.noindex) {
    sitemap.push({ loc: ctx.abs(page.slug ? `${page.slug}/` : ''), priority: page.slug ? (page.slug === 'reserve' ? '0.9' : '0.8') : '1.0' });
  }
}

writeFileSync(join(OUT, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemap.map((u) => `  <url><loc>${u.loc}</loc><lastmod>${SITE.updated}</lastmod><priority>${u.priority}</priority></url>`).join('\n')}
</urlset>
`);

writeFileSync(join(OUT, 'robots.txt'), SITE.launched
  ? `User-agent: *\nAllow: /\n\nSitemap: ${SITE.url.replace(/\/$/, '')}/sitemap.xml\n`
  : `# Preview build: not launched. Flip launched: true in site.config.mjs at launch.\nUser-agent: *\nDisallow: /\n`);

writeFileSync(join(OUT, '.nojekyll'), '');
if (SITE.customDomain) writeFileSync(join(OUT, 'CNAME'), `${SITE.customDomain}\n`);

console.log(`Built ${PAGES.length} pages into ${OUT} (${SITE.launched ? 'LAUNCHED' : 'preview, noindex'}).`);
